/** @type {import('tailwindcss').Config} */

const { colors, spacing, layout, typography, shadows, breakpoints, gradients } = require('./src/design-system/tokens');

module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        'chillax': ['Chillax', 'sans-serif'],
        'satoshi': ['Satoshi', 'sans-serif'],
        'cairo': ['Cairo', 'sans-serif'],
        sans: typography['font-family'].base.split(','),
        heading: typography['font-family'].heading.split(','),
        brand: typography['font-family'].brand.split(','),
        arabic: ['Cairo', ...typography['font-family'].base.split(',')],
        'arabic-heading': ['Cairo', ...typography['font-family'].heading.split(',')],
        catalog: ['Playfair Display', ...typography['font-family'].heading.split(',')],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: colors['light-green'][1],
          100: colors['light-green'][2],
          200: colors['light-green'][3],
          300: colors['light-green'][4],
          400: colors['dark-green'][4],
          500: colors['dark-green'][3],
          600: colors['dark-green'][2],
          700: colors['dark-green'][1],
          800: colors['dark-green'][7],
          900: colors['dark-green'][5],
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Custom DikaFood colors from design system
        ...colors['dark-yellow'],
        ...colors['light-yellow'],
        ...colors['dark-green'],
        ...colors['light-green'],
        ...colors['dark-purple'],
        ...colors['light-purple'],
        'dark-yellow': colors['dark-yellow'],
        'light-yellow': colors['light-yellow'],
        'dark-green': colors['dark-green'],
        'light-green': colors['light-green'],
        'dark-purple': colors['dark-purple'],
        'light-purple': colors['light-purple'],
        'logo-green': colors.logo.green,
        'logo-lime': colors.logo.lime,
        'logo-brown': '#8B5A2B',
        'neutral': colors['neutral'],
        'feedback': colors['feedback'],
        blue: {
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        yellow: {
          100: '#fef9c3',
          200: '#fef08a',
          300: '#fde047',
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
        },
      },
      spacing: {
        ...spacing.desktop,
        ...spacing.tablet,
        ...spacing.mobile,
        'navbar': '80px',
        'navbar-mobile': '56px',
      },
      maxWidth: {
        'layout': layout['max-width'],
      },
      padding: {
        'section': layout['section-padding'],
      },
      height: {
        'navbar': layout['navbar-height'],
        'navbar-mobile': layout['navbar-height-mobile'],
        'product-card': '400px',
      },
      aspectRatio: {
        'product-card': '0.7',
      },
      lineHeight: {
        tight: typography['line-height'].tight,
        base: typography['line-height'].base,
        relaxed: typography['line-height'].relaxed,
      },
      fontWeight: {
        light: typography['font-weight'].light,
        normal: typography['font-weight'].normal,
        medium: typography['font-weight'].medium,
        semibold: typography['font-weight'].semibold,
        bold: typography['font-weight'].bold,
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      boxShadow: {
        'sm': shadows.sm,
        'md': shadows.md,
        'lg': shadows.lg,
        'xl': shadows.xl,
      },
      screens: {
        'xs': '475px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
        // Custom breakpoints from design system
        'mobile': `${breakpoints.mobile}px`,
        'tablet': `${breakpoints.tablet}px`,
        'laptop': `${breakpoints.laptop}px`,
        'desktop': `${breakpoints.desktop}px`,
        'widescreen': `${breakpoints.widescreen}px`,
      },
      backgroundImage: {
        ...gradients,
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}